language: dart

dart:
  - stable
  - dev

install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=~/build/parse-community/Parse-SDK-Flutter/flutter/bin:$PATH
  - flutter doctor

script:
  - (cd packages/dart && pub get)
  - (cd packages/dart && pub run test)
  - (cd packages/flutter && flutter pub get)
  - (cd packages/flutter && flutter test --no-pub test/)

cache:
  directories:
    - "$HOME/.pub-cache"