name: parse_server_sdk_flutter
description: Flutter plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 2.0.1
homepage: https://github.com/phillwiggins/flutter_parse_sdk

environment:
  sdk: ">=2.10.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk:
    git:
      url: https://github.com/maxiundtesa/Parse-SDK-Flutter.git
      path: packages/dart

  # Networking
  dio: ^4.0.0-beta7
  connectivity: ^3.0.2 # only used in the flutter part

  #Database
  shared_preferences: ^2.0.4 # only used in the flutter part

  # Utils
  path_provider: ^2.0.1 # only used in the flutter part
  package_info: ^0.4.3 # only used in the flutter part
  sembast: ^2.4.7+6 # required for transitive use only
  path: ^1.7.0 # required for transitive use only

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
